ibw_jobeet:
    resource: "@IbwJobeetBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#FosUserBundle
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
